---
version: '3'
services:
  solr:
    image: solr
    container_name: local_solr
    volumes:
      - data:/var/solr
    ports:
     - 8983:8983
    command: 
     - solr-precreate
     - amazon_products
    mem_limit: 4g
    restart: always
volumes:
  data:
...
